FROM ghcr.io/astral-sh/uv:0.10-python3.14-trixie-slim

ENV PATH="/workspaces/my-local-ai-environment/.venv:$PATH"

# Need to enable this since docker doesn't support hardlinking
ENV UV_LINK_MODE=copy

# Install the fastmcp CLI
RUN uv tool install 'fastmcp >= 3.0.0b'